lib/engpin_web/router.ex
defmodule EngpinWeb.Router do
  use EngpinWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EngpinWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/videos", VideoController
    get "/watch/:id", WatchController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", EngpinWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EngpinWeb.Telemetry
    end
  end
end

lib/engpin/teachers/video.ex
defmodule Engpin.Teachers.Video do
  use Ecto.Schema
  import Ecto.Changeset

  schema "videos" do
    field :content_type, :string
    field :filename, :string
    field :path, :string
    field :title, :string
    field :video_file, :any, virtual: true

    timestamps()
  end

  @required_fields ~w(title video_file)a
  @optional_fields ~w(filename)a
  @doc false
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> put_video_file()
  end

  def put_video_file(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{video_file: video_file}} ->
        path = Ecto.UUID.generate() <> Path.extname(video_file.filename)

        changeset
        |> put_change(:path, path)
        |> put_change(:filename, video_file.filename)
        |> put_change(:content_type, video_file.content_type)

      _ ->
        changeset
    end
  end
end

lib/engpin_web/controllers/video_controller.ex
defmodule EngpinWeb.VideoController do
  use EngpinWeb, :controller

  import Engpin.Util, only: [build_video_path: 1]

  alias Engpin.Teachers
  alias Engpin.Teachers.Video

  def index(conn, _params) do
    videos = Teachers.list_videos()
    render(conn, "index.html", videos: videos)
  end

  def new(conn, _params) do
    changeset = Teachers.change_video(%Video{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"video" => video_params}) do
    temp_path = video_params["video_file"].path
    video_params = update_path(video_params, "priv/static/videos#{video_params["video_file"].filename}")
    case Teachers.create_video(video_params) do
      {:ok, video} ->
        save_file(video, temp_path)

        conn
        |> put_flash(:info, "Video created successfully.")
        |> redirect(to: Routes.video_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  # def create(conn, %{"video" => video_params}) do
  #  case Teachers.create_video(video_params) do
  #    {:ok, video} ->
  #      conn
  #      |> put_flash(:info, "Video created successfully.")
  #      |> redirect(to: Routes.video_path(conn, :show, video))

  #    {:error, %Ecto.Changeset{} = changeset} ->
  #      render(conn, "new.html", changeset: changeset)
  #  end
  # end

  def show(conn, %{"id" => id}) do
    video = Teachers.get_video!(id)
    render(conn, "show.html", video: video)
  end

  def edit(conn, %{"id" => id}) do
    video = Teachers.get_video!(id)
    changeset = Teachers.change_video(video)
    render(conn, "edit.html", video: video, changeset: changeset)
  end

  def update(conn, %{"id" => id, "video" => video_params}) do
    video = Teachers.get_video!(id)

    case Teachers.update_video(video, video_params) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video updated successfully.")
        |> redirect(to: Routes.video_path(conn, :show, video))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", video: video, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    video = Teachers.get_video!(id)
    {:ok, _video} = Teachers.delete_video(video)

    conn
    |> put_flash(:info, "Video deleted successfully.")
    |> redirect(to: Routes.video_path(conn, :index))
  end

  defp  save_file(video, temp_path) do
    video_path = build_video_path(video.filename)

    unless File.exists?(video_path) do
      video_path |> Path.dirname() |> File.mkdir_p()
      File.copy!(temp_path, video_path)
    end
  end

  defp update_path(video_params, new_path) do
    Map.update(video_params, "video_file", nil, fn video_file ->
      Map.put(video_file, :path, new_path)
    end)
  end
end

lib/engpin_web/views/video_view.ex
defmodule EngpinWeb.VideoView do
  use EngpinWeb, :view
end

lib/engpin_web/templates/video/edit.html.eex
<h1>Edit Video</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.video_path(@conn, :update, @video)) %>

<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>

lib/engpin_web/templates/video/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, required: true, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :video_file, "Video", class: "control-label" %>
    <%= file_input f, :video_file, required: true, class: "form-control" %>
    <%= error_tag f, :video_file %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/engpin_web/templates/video/index.html.eex
<h1>Listing Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Filename</th>
      <th>Content type</th>
      <th>Path</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for video <- @videos do %>
    <tr>
      <td><%= video.title %></td>
      <td><%= video.filename %></td>
      <td><%= video.content_type %></td>
      <td><%= video.path %></td>

      <td>
        <span><%= link "Show", to: Routes.video_path(@conn, :show, video) %></span>
        <span><%= link "Edit", to: Routes.video_path(@conn, :edit, video) %></span>
        <span><%= link "Delete", to: Routes.video_path(@conn, :delete, video), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Video", to: Routes.video_path(@conn, :new) %></span>

lib/engpin_web/templates/video/new.html.eex
<h1>New Video</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.video_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>

lib/engpin_web/templates/video/show.html.eex
<h2>Show Video</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @video.title %>
  </li>

</ul>

<video id="my-video" class="video-js" controls preload="none" width="640" height="264" data-setup="{}">
  <source src="<%= Routes.watch_path(@conn, :show, @video) %>" type='<%= @video.content_type %>'>
  <p class="vjs-no-js">
    To view this video please enable JavaScript, and consider upgrading to a web browser that
    <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
  </p>
</video>

<span><%= link "Edit", to: Routes.video_path(@conn, :edit, @video) %></span>
<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>